spring:
  application:
    name: HospitalBooking

  datasource:
    url: jdbc:postgresql://localhost:5432/Hospitaldb
    username: postgres
    password: Ind*#@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true